<a href="https://colab.research.google.com/github/G750cloud/20MA573/blob/master/Copy_of_Untitled19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import scipy.stats as ss

def Euler_CEV(S0,o_type,T,N,n,K,r,y,vol):
  sum_value=0
  w=T/N
  for j in range(n):
    S=S0
    for i in range(N):
      z=np.random.normal()
      S=S+0.03*S*w+vol*(S**y)*np.sqrt(w)*z
    if (S-K)*o_type >0 :
      sum_value+=(S-K)*o_type
  return np.exp(-r*T)*sum_value/n

In [0]:
Euler_CEV(100,1,1,1000,1000,97,0.0475,1,0.2)

10.418866201720734

In [0]:
!git clone https://github.com/songqsh/20s_ma573.git
%cd 20s_ma573/src/

np_option_data = np.loadtxt('20optiondata2.dat', comments='#', delimiter=',')
print('>>>otype,        maturity,  strike,       option_price')
print(np_option_data)

def maturity_choice(mat_choice):
  option_data=np_option_data[np_option_data[:,1] == mat_choice]
  return option_data

op_list1=maturity_choice(5/12)

Cloning into '20s_ma573'...
remote: Enumerating objects: 88, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 301 (delta 49), reused 44 (delta 20), pack-reused 213
Receiving objects: 100% (301/301), 2.15 MiB | 26.18 MiB/s, done.
Resolving deltas: 100% (158/158), done.
/content/20s_ma573/src
>>>otype,        maturity,  strike,       option_price
[[  1.           0.16666667  97.           5.32705461]
 [  1.           0.16666667  99.           3.86224255]
 [  1.           0.16666667 101.           2.7204371 ]
 [  1.           0.16666667 103.           2.1202793 ]
 [  1.           0.41666667  97.           7.23756307]
 [  1.           0.41666667  99.           5.95053461]
 [  1.           0.41666667 101.           5.2640122 ]
 [  1.           0.41666667 103.           4.97493422]]


In [0]:
import scipy.optimize as so

def error_function(vol_y):
  error=0
  vol=vol_y[0]
  y=vol_y[1]
  a=0
  for i in np.arange(len(op_list1)):
    error+=((op_list1[i,3])-Euler_CEV(100,1,5/12,1000,1000,op_list1[i,2],0.0475,y,vol)) **2
  return error

initial_guess=[0.1,1]
print(so.fmin(error_function,initial_guess,xtol=0.0001,ftol=0.0001,maxiter=None, maxfun=None))